pipeline {
    agent any
    stages {

        stage('Build Backend Image') {
            steps {
                sh '''
                docker rmi -f backend-app || true
                docker build -t backend-app CC_LAB-6/backend
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker rmi -f frontend-app || true
               docker build -t frontend-app CC_LAB-6/nginx
                '''
            }
        }

        stage('Deploy Backend Containers') {
            steps {
                sh '''
                docker network create app-network 2>/dev/null || true
                docker rm -f backend1 backend2 2>/dev/null || true
                docker run -d --name backend1 --network app-network backend-app
                docker run -d --name backend2 --network app-network backend-app
                '''
            }
        }

        stage('Deploy NGINX Load Balancer') {
            steps {
                sh '''
                docker rm -f nginx-lb 2>/dev/null || true
                docker run -d \
                  --name nginx-lb \
                  --network app-network \
                  -p 80:80 \
                  frontend-app
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully. NGINX load balancer is running.'
        }
        failure {
            echo 'Pipeline failed. Check console logs for errors.'
        }
    }
}
